### ISSUE TITLE
Got an error inputting an image set of 1334x1553 pixels

### ISSUE THREAD

**Issue by YahiyaHussain** [biomedia-mira/istn#7]
![image](https://user-images.githubusercontent.com/34356761/74341173-3ee61580-4d75-11ea-9882-8acc18299807.png)

I was successful in having the program run to completion and viewing the results on tensorboard for the original example plus custom data sets of 70 image pairs (main and seg for both training and validation) that were 128x128, 256x256, 1024x1024, and 512x600. However when I ran it for the image set where each image is 1334x1553 pixels, I got this strange cryptic error. Is there a constraint on this istn-reg tool that I need to know, is there a bug, or is there something otherwise that I need to do in order to run the program with my desired image set.

**Comment by mauinz** [comment]
This is because the ITN network we used down samples and up samples by factors of 2, 1334 not having a prime decomposition with enough 2s seems to be the issue (a round error essentially).

You could either pad your data or change the ITN slightly to take this into consideration, let me know if this solves your issue.

**Comment by YahiyaHussain** [comment]
I have tested a bunch of sizes and have confirmed your suspicion. I reproduced the error by doing the 729x729 sized image whose dimensions are odd. 486x486 also errored out because it is only divisible by 2 and not a higher power of 2. 324x324 worked however because its dimensions are divisible by 4. I thus went on to test a modified version of the image set that is 1336x1556 as opposed to 1335x1553, the former of which has both the length and width of the image divisible by 4 and the latter of which has niether divisible by 4. And it worked so padding seems to be a definite solution. 

However I am curious about your idea for changing the ITN slightly. I have found where the ITN is defined in pymira:
![image](https://user-images.githubusercontent.com/34356761/74381471-82fb0980-4db9-11ea-8d43-b98d594beb71.png)

But how would I go about changing it to not have a rounding error break images of the wrong dimensions while still retaining the capabilities of the model?

**Comment by bglocker** [comment]
I wouldn't be too worried about changing the architecture of the ITN. We have never really optimised over this, as the whole ISTN approach is more of a conceptual idea, rather than saying that the exact architectures we employed are the best for this. So feel free to tinker around with both the ITN and the STN specifics.

Having said this, for the particular problem of varying resolutions, you may even want to consider to do a post-processing of the ITN output to bring it back to the resolution of the input (e.g., via simple padding). You just need to make sure to pad on the correct ends, to not introduce a shift of the anatomical structures.
